[View in Colaboratory](https://colab.research.google.com/github/naoyamaguchi/python-data-analytics/blob/master/numpy/numpy.ipynb)

In [0]:
import numpy as np

In [0]:
# 配列の生成

In [2]:
np.arange(1, 10) 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(1, 10, 2) 

array([1, 3, 5, 7, 9])

In [5]:
np.linspace(1, 2, 5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [7]:
np.array([1, 0, 1], dtype='float32')

array([1., 0., 1.], dtype=float32)

In [9]:
x = np.array([1, 2, 3, 4, 5])
 
# 0番目にアクセス
x[0] 

1

In [10]:
# スライスで0番目から2番目未満にアクセス
x[0:2]

array([1, 2])

In [11]:
# 最後の要素にアクセス
x[-1]

5

In [0]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [13]:
x + y

array([5, 7, 9])

In [0]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
b = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [15]:
a + b

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [16]:
# 一般的な行列演算(内積)ではないことに注意
a * b

array([[ 10,  40,  90],
       [160, 250, 360],
       [490, 640, 810]])

In [17]:
# 内積はこっち
np.dot(a, b)

array([[ 300,  360,  420],
       [ 660,  810,  960],
       [1020, 1260, 1500]])